"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Space Invaders.py']
DATA_FILES = ['background-black.png', 'pixel_laser_blue.png', 'pixel_laser_green.png', 'pixel_laser_red.png', 'pixel_laser_yellow.png', 'pixel_ship_blue_small.png', 'pixel_ship_green_small.png', 'pixel_ship_red_small.png', 'pixel_ship_yellow.png']
OPTIONS = {'includes':['pygame', 'os', 'time', 'random', 'sys']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
